In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.array(12)
print(x)
print(x.ndim)

12
0


In [3]:
x = np.array([12,3,4,56,7])
print(x)
print(x.ndim)

[12  3  4 56  7]
1


In [4]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [5]:
x = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ],
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(x.ndim)
print(x.shape)
print(type(x))

3
(4, 2, 2)
<class 'numpy.ndarray'>


In [6]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()
my_slice = train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [7]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j] = max(x[i][j], 0)
    return x

x = np.array([
    [1, -1],
    [-2, 1]
])

print(naive_relu(x))

[[1 0]
 [0 1]]


In [8]:
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([5, 6])
c = np.array([7, 8])
print(a)
print(a.T)
print(b)
print(b.T)
print(c)
print(c.T)
print(type(b))
print(type(c.T))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[5 6]
[5 6]
[7 8]
[7 8]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
f = np.dot(a.T, b)
print(f)

[23 34]
